// <auto-generated />
namespace CalculadoraConsumoCombustivel.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class CriarTabelaMediaConsumo1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CriarTabelaMediaConsumo1));
        
        string IMigrationMetadata.Id
        {
            get { return "202604291526441_CriarTabelaMediaConsumo1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
